### ISSUE TITLE
'USB_VID' was not declared in this scope 

### ISSUE THREAD

**Issue by Ciph3rCat** [tobozo/WUD-Ducky#4] opened 2022-01-26 05:57 UTC
I am trying to flash from active branch, and getting this error, 'USB_VID' was not declared in this scope.

How can I fix this? 

The main branch does flashes successfully and wifi becomes available but webpage is not accessible at 192.168.4.1.

**Comment by tobozo** [comment] 2022-01-26 10:39
hey @Ciph3rCat thanks for your feedback :+1: 

You can fix that by uncommenting the declarations in [USBConfig.h](https://github.com/tobozo/WUD-Ducky/blob/arduino-esp32-2.0.2/USBDevices/USBConfig.h).

Keep in mind those declarations will be ignored (and overriden by Espressif system defaults) as soon as you enable "USBCDC on boot" in the Arduino tools menu.

**Comment by Ciph3rCat** [comment] 2022-01-26 11:13
Thanks for the prompt reply. Both solutions worked (uncommenting lines and enabling cdc on boot). However now there is no wifi available, the red light is constantly on. Any ideas?

**Comment by tobozo** [comment] 2022-01-26 11:49
I had this symptom a few minutes ago with cdc on boot **disabled**, not easy to debug this one when serial is clogged :-)

For some reason I'm trying to figure out, it can't work when the 'cdc on boot' option is disabled, which is fine since we need cdc anyway.

Here's what my menu looks like:

![image](https://user-images.githubusercontent.com/1893754/151155243-d3332ded-0d9b-4308-997d-a0a8742e3379.png)

I've created a custom [board](https://github.com/tobozo/WUD-Ducky/tree/arduino-esp32-2.0.2/board) folder profile in my Arduino IDE, it's a copy of the original esp32s2-dev profile, with most options prechecked and a modified pins_arduino.h file. 

![image](https://user-images.githubusercontent.com/1893754/151157588-7c19015a-6afc-4af5-9472-e2a2520f47c7.png)

I've also pushed some minor changes.

**Comment by Ciph3rCat** [comment] 2022-01-26 13:05
I matched the configuration and flashed latest commit. But got same results then I realize Windows displays 'usb does not recognised' after few minutes. I think, the culprit is 'zadig' software because I was having difficulty in putting board into flash mode and thought maybe drivers are missing and read somewhere about this tool and installed drivers using this. Now I don't know if there's anyway to revert those changes or maybe I have to do fresh Windows installation. 😕

I tried the board on mac and it displayed general error, 'unknown keyboard detected, press ant key to identify the keyboard' which is not possible, however the wifi was available and web interface was accessible.

If you have any suggestions please share with me, and I'm planning to contribute in the documentation once I'll solve the current bugs.

By the way, it turns on led, where can I update the code to disable that?

**Comment by tobozo** [comment] 2022-01-26 14:28
interesting, I haven't tested much the web UI (most tests were made thru the serial interface) so I'll welcome your feedback.

I just tried to plug the WUD on a windows laptop (never plugged there before but has an installation of Arduino IDE) and the USB drive got detected, mounted and even repaired. 

This only happened once, after unplugging and re-pluging the USB Pendrive can't be detected anymore and the led is always on.

I can't test much for now since the OS choose that moment to start a very long windows update process :facepalm: , but I'll check the detections status of the other USB devices as soon as it's finished.

thoughts about zadig: maybe it tried to identify `dead:b33f` or `cafe:deca` and got the wrong idea (those are dummy IDs)?  

However the device descriptor in the USB packets can't lie, so zadig should at least idenfity a driver for the USBSerial interface, and not ask to install anything for mouse or keyboard since those are already part of the system.

I'm not sure about the the mac though, sending the key from the web interface would seem the obvious thing to do but I haven't tested that part much since I've implemented SpaceHuhn's WiFiDuck syntax.

Otherwise there may be something interesting to implement on the ESP side such as mocking an existing model, you can experiment with that from the pins_arduino.h file.

to turn the led off send this command: `LED 0`

However in a successful boot scenario it should blink a few times an turn itself off.

**Comment by Ciph3rCat** [comment] 2022-01-28 06:24
You are right there's some weird behaviour on windows, and you mentioned it will turn off led after successful connection but that doesn't happen once. I have tried different operating system but it is always on, however on linux and mac the wifi connection does show and opens website fine.

Questions:
1. How do I open serial connection with the board? (tried in putty and arduino serial monitor after putting in dev mode, always results in empty screen, also tried different baud rate and regular mode)

2. The yesterday commit isn't compiling, USB_PID was not declared in this scope. How this can be fixed?

3. In Linux, I tried to send keystrokes like this: http://192.168.4.1/key?=hello but those wasn't sent to linux box, just echoed in browser. From the homepage, I uploaded a text document and then click on run payload, the '6' character was sent to the box. The document contains a lot of text and only one character was sent, tried repeatedly and same results. That means, it is detected as keyboard but there's something wrong with argument parsing. Any ideas? 

4. I'm trying to learn the code but doesn't make much sense, does learning c++ syntax will help or ?

**Comment by Ciph3rCat** [comment] 2022-02-01 04:28
It's been several days, can you please respond to 2nd and 3rd point at least?

**Comment by tobozo** [comment] 2022-02-01 08:54
Hi, sorry about that, I got carried away by the Web UI changes.

I suggest you try the latest changes on the secondary branch after clearing up your spiffs partition.

> How do I open serial connection with the board

Same as you did, putty, arduino, serial monitor. but there's no welcome message and the port number may change on every reboot. Did you try to issue the "help" command ?

> The yesterday commit isn't compiling, USB_PID was not declared in this scope.

This was fixed a couple of commits ago

>  something wrong with argument parsing. 

Tried to fix that too but playing with the URL bar on a smartphone isn't my favourite QA activity so I'll probably go with a live-quacker and add a textarea plus a send button.

I've added the possibility to edit SPIFFS files from the webUI, so you should be able to play with that at least.

> I'm trying to learn the code but doesn't make much sense, does learning c++ syntax will help or ?

Sure, be careful it's highly addictive :wink:

**Comment by Ciph3rCat** [comment] 2022-02-01 12:49
Thanks for the reply, the latest changes fixed the `USB_PID` bug and the web interface was accessible.

When I try to create serial connection in arduino ide, it does open and I can type commands but the content disappear when I press 'send' button.

And in putty, it opens blank screen where I can't type or do anything. However I noticed, it does establish connection because when I open in putty and then in arduino, it says "port is busy". Not sure, what I'm missing here. ☹️

I tried to run a simple payload: `PrintLine : hello` and it send some text to the machine but it was just some gibberish, not the actual text. Does this works fine in serial mode and what could be wrong here?

**Comment by tobozo** [comment] 2022-02-01 13:23
> but the content disappear when I press 'send' button.

Try to press enter instead of the send button? dunno why it fails with the button though, could be a `\r\n` vs `\n` separator issue in the `PrintLine` command. 

Also I'm using this serial console option 

![image](https://user-images.githubusercontent.com/1893754/151975498-08ca6f6c-7a24-4c42-8e90-20e28a19dfac.png)

I'll probably remove the `PrintLine` command soon.
The `String` command works fine anyway, and the `:` isn't required any more since it's now using the same ducky commands as Spacehuhn's WiFiDuck.

**Comment by Ciph3rCat** [comment] 2022-02-01 16:38
Awesome it worked almost fine with the String, except the casing, "Hello" was printed as "hELLO".

I tried with the enter key but same issue, maybe it is due to some windows issue, I'll try on linux after setting up dev environment.

**Comment by tobozo** [comment] 2022-02-01 20:00
> "Hello" was printed as "hELLO"

lol pwned by `CAPSLOCK` command :-)

**Comment by tobozo** [comment] 2022-02-04 20:09
Last commit moved the webserver filesystem from SPIFFS to the more reliable LittleFS partitions, you may want to re-upload the data folder as LittleFS to prevent weird behaviour if you're using this version.

There's also a new text field at the bottom (with auto suggest) to send ducky commands, it's not multiline though.

![image](https://user-images.githubusercontent.com/1893754/152596077-b258dfd8-21c2-4c68-bd35-7f044d40dc72.png)

**Comment by Ciph3rCat** [comment] 2022-02-05 10:27
That's good to know, but something is breaking from latest commit. I'm getting a generic error: "unable to compile for esp32".

**Comment by Ciph3rCat** [comment] 2022-02-05 10:29
By the way, do we need to manually upload data folder? (doesn't it automatically update when flashing)

**Comment by tobozo** [comment] 2022-02-05 11:29
> unable to compile for esp32" 

Maybe you need to select "esp32-s2" from the boards menu ?

> doesn't it automatically update when flashing

Nope, it only calculates the partition geometry and writes the firmware in the application partition, leaving the rest unchanged.

Flashing the LittleFS partition requires to put the ESP32-S2/WUD in flash mode using the magnet though, and manually resetting after.

![image](https://user-images.githubusercontent.com/1893754/152640186-73697832-fd51-434b-8473-4fcd49d1539c.png)

![image](https://user-images.githubusercontent.com/1893754/152640209-0427d10a-e00a-4727-bc1a-81a5d949f134.png)

**Comment by Ciph3rCat** [comment] 2022-02-05 16:32
I have selected "ESP32S2 Dev Module" board and it use to work with previous commit.

Your tools menu looks slightly different, I don't see any option for flashing data. The board options start right after wifi option. Do I need to enable/install anything to get those options?

**Comment by tobozo** [comment] 2022-02-05 18:22
> I need to enable/install anything to get those options?

hmm maybe, I've had those tools for a while so I can't remember how they landed in my IDE.

here's my `$HOME/Arduino` folder for what it's worth. Note this the same folder from the Arduino IDE Preferences for "Sketchbook location" (the first property in the preferences window).

I've unfolder everything under the `$HOME/Arduino/tools` folder, those files can be found on github, most are managed by me-no-dev.

https://github.com/me-no-dev/arduino-esp32fs-plugin
https://github.com/me-no-dev/EspExceptionDecoder

The one you're looking for is probably `$home/Arduino/tools/ESP32FS/tool/esp32fs.jar`.
I've found the Exception decoder completely useless with the WUD though.

Once you've unzipped the jar files in the right place (triple-check the path with the screenshot), restart the IDE and check your tools menu, the options should be there.

![image](https://user-images.githubusercontent.com/1893754/152653822-6e3d6d53-f2e6-4cea-8b23-c98bbceec94d.png)

**Comment by Ciph3rCat** [comment] 2022-02-06 07:51
Any idea on: "unable to compile for esp32"?

Thanks, I was able to upload data using plugin.

**Comment by tobozo** [comment] 2022-02-06 11:56
> Any idea on: "unable to compile for esp32"?

not without additional information, output verbosity and compiler warnings need to be enabled to see more on that error.

![image](https://user-images.githubusercontent.com/1893754/152679270-959338f5-e8b3-49a9-a77d-9be7e47d90b2.png)

I haven't changed anything since last commit and it compiles in my IDE.

**Comment by Ciph3rCat** [comment] 2022-02-06 14:07
Here is the error log:

```
[snip] 
In file included from C:\Users\Ciph3rCat\Documents\WUD-Ducky\WiFiDuck\WebServer.cpp:30,
Multiple libraries were found for "WiFi.h"
 Used: C:\Users\Ciph3rCat\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.2\libraries\WiFi
                 from C:\Users\Ciph3rCat\WUD-Ducky\arduino-esp32-2.0.2\WUD-Ducky\WUD-Ducky.ino:37:
 Not used: C:\Program Files (x86)\Arduino\libraries\WiFi
 C:\Users\Ciph3rCat\Documents\WUD-Ducky\WiFiDuck\WebUI.cpp:46:10: fatal error: ArduinoJson.h: No such file or directory
Multiple libraries were found for "SD.h"
 #include <ArduinoJson.h>
 Used: C:\Users\Ciph3rCat\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.2\libraries\SD
          ^~~~~~~~~~~~~~~
 Not used: C:\Program Files (x86)\Arduino\libraries\SD
compilation terminated.
Using library SD at version 2.0.0 in folder: C:\Users\Ciph3rCat\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.2\libraries\SD 
Using library FS at version 2.0.0 in folder: C:\Users\Ciph3rCat\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.2\libraries\FS 
Using library SPI at version 2.0.0 in folder: C:\Users\Ciph3rCat\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.2\libraries\SPI 
Using library USB at version 2.0.0 in folder: C:\Users\Ciph3rCat\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.2\libraries\USB 
Using library LittleFS at version 2.0.0 in folder: C:\Users\Ciph3rCat\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.2\libraries\LittleFS 
Using library Preferences at version 2.0.0 in folder: C:\Users\Ciph3rCat\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.2\libraries\Preferences 
Using library ESPmDNS at version 2.0.0 in folder: C:\Users\Ciph3rCat\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.2\libraries\ESPmDNS 
Using library WiFi at version 2.0.0 in folder: C:\Users\Ciph3rCat\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.2\libraries\WiFi 
Using library WebServer at version 2.0.0 in folder: C:\Users\Ciph3rCat\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.2\libraries\WebServer 
exit status 1
Error compiling for board ESP32S2 Dev Module.
```

**Comment by tobozo** [comment] 2022-02-06 14:16
`fatal error: ArduinoJson.h: No such file or directory`

This is basic Arduino troubleshooting, so I'll only give a basic hint: use a search engine and paste the error message in the search field :stuck_out_tongue_winking_eye:

**Comment by j1t077** [comment] 2022-03-18 11:49
I have this problem: And it's all set up correctly (or so it seems). I tried esp32s2-WUD and got this error, and I tried with esp32s2-dev Module getting a different error (error: 'class fs::SDFS' has no member named 'sectorSize'; did you mean 'cardSize'? size_t sectorSize = SD.sectorSize();) 

Attached image of the error using esp32s2-WUD.

![](https://raw.githubusercontent.com/j1t077/WUD-Ducky/J1t077/extras/Buena-WUD.png)


tanks.

**Comment by tobozo** [comment] 2022-03-18 12:02
@j1t077 the lack of `disabled` choice indicates your platform.local.txt contains an older version of the `esp32s2_WUD` board definition.

If in doubt, just use the esp32s2_dev profile.

`fs::SDFS' has no member named 'sectorSize';`

this error is odd, maybe some older version of the SD library is interferring ?

**Comment by GippokratOA** [comment] 2022-03-21 15:34
> (error: 'class fs::SDFS' has no member named 'sectorSize'; did you mean 'cardSize'? size_t sectorSize = SD.sectorSize();)


@j1t077 Hi, I decided to come back after a short break and now I have the same error. Have you already solved this problem?

**Comment by GippokratOA** [comment] 2022-03-21 15:37
Changing of SD version didn't help me..

**Comment by tobozo** [comment] 2022-03-21 15:57
I just found the source of the error and pushed a fix, sorry about the mess.

**Comment by GippokratOA** [comment] 2022-03-21 16:12
Ok, it is gone. But now there is one more. `error: 'class fs::SDFS' has no member named 'numSectors'
     size_t numSectors = SD.numSectors();
`

**Comment by tobozo** [comment] 2022-03-21 16:34
sorry I just realized was using a locally modified version of SD, since I forgot to submit the changes on the espressif repo those aren't documented :facepalm: 
 
I've pushed a fix for the missing `numSectors()` method but the sector size is now hardcoded (512), and it'll break with non standard partitions.

Let's hope this [PR](https://github.com/espressif/arduino-esp32/pull/6457/files) gets approved.

**Comment by GippokratOA** [comment] 2022-03-21 18:56
Well, compilation went succesfully. Now I have some problems with uploading files on ducky. When I trying upload some file, it doesnt appear in this list.
![image](https://user-images.githubusercontent.com/51450242/159344215-96b5833e-e3e4-4dc9-831d-2eb6c05bb073.png)
![image](https://user-images.githubusercontent.com/51450242/159344265-65feea2b-62dc-4c6d-803d-b62462ac9bb5.png)

**Comment by GippokratOA** [comment] 2022-03-21 18:56
Log file has not any useful

**Comment by tobozo** [comment] 2022-03-21 19:15
how's the info window ? looks like SPIFFS wasn't formatted/mounted.

![image](https://user-images.githubusercontent.com/1893754/159347340-2f75759b-3bcd-496c-9678-8eb7a522b9a0.png)

**Comment by GippokratOA** [comment] 2022-03-21 19:21
![image](https://user-images.githubusercontent.com/51450242/159348208-267202bd-ebcc-4e87-b423-f55fb535fb68.png)
Well, thats strange

**Comment by GippokratOA** [comment] 2022-03-21 19:25
I reconnected stick. Now when I try to reach the part of web-ui after disclaimer, ducky just restarts.

**Comment by tobozo** [comment] 2022-03-21 19:32
Actually it's LittleFS now, I'll update the label to make that more obvious.

If you formatted SPIFFS this may explain the crash when you access the filesystem.

Also there's a probable fix for the file being uploaded but not created, I can't push a fix on that file without pushing new bugs but I've been able to reproduce and fix it by modifying this line in `WiFiDuck/WebServer.cpp` around line 176 :

    fsUploadFile = LittleFS.open( "/" + filename, "w");

It was missing the "/".

Thanks a lot for your feedback :+1:

**Comment by GippokratOA** [comment] 2022-03-22 14:28
Oh, now I have some logs.
`[@00:02:59.929] SD Card Mount attempt: 2
[@00:03:00.644] SD Card Mount attempt: 3
[@00:03:01.359] SD Card Mount attempt: 4
[@00:03:02.074] SD Card Mount attempt: 5
[@00:03:02.789] SD Card Mount attempt: 6
[@00:03:03.504] SD Card Mount attempt: 7
[@00:03:04.219] SD Card Mount attempt: 8
[@00:03:04.934] SD Card Mount attempt: 9
[@00:03:05.649] SD Card Mount attempt: 10
[@00:03:06.364] SD Card Mount attempt: 11
[@00:03:06.464] SD Card Mount Failed
[@00:03:06.464] Error, PenDrive disabled
[@00:03:06.464] SD Card not present, spawning fake partition
[@00:03:06.848] LittleFS failed!
...
...

[@00:05:05.372] LittleFS failed!
[@00:05:10.517] [HTTP] Rewriting root path to index.html
[@00:05:10.517] [HTTP] Serving 'index.html' from job
[@00:05:10.557] [HTTP] Serving 'styles.css' from flash memory
[@00:05:10.566] [HTTP] Serving 'script.js' from flash memory
[@00:05:10.575] [HTTP] Internal path 'Quack.wav' not found
[@00:05:10.619] [HTTP] Serving 'list' from job
[@00:05:18.174] [HTTP] Receiving file: ESP32FS-1.0.zip
[@00:05:18.187] [HTTP] File Size: 7387
[@00:05:18.187] [HTTP] File uploaded successfully
[@00:05:18.190] [HTTP] Internal path 'upload' not found
[@00:05:18.200] [HTTP] Rewriting root path to index.html
[@00:05:18.200] [HTTP] Serving 'index.html' from job
[@00:05:18.231] [HTTP] Rewriting root path to index.html
[@00:05:18.232] [HTTP] Serving 'index.html' from job
[@00:05:18.267] [HTTP] Serving 'styles.css' from flash memory
[@00:05:18.277] [HTTP] Serving 'script.js' from flash memory
[@00:05:18.283] [HTTP] Internal path 'Quack.wav' not found
[@00:05:18.328] [HTTP] Serving 'list' from job
[@00:05:20.281] [HTTP] Rewriting root path to index.html
[@00:05:20.282] [HTTP] Serving 'index.html' from job
[@00:05:20.321] [HTTP] Serving 'styles.css' from flash memory
[@00:05:20.330] [HTTP] Serving 'script.js' from flash memory
[@00:05:20.341] [HTTP] Internal path 'Quack.wav' not found
[@00:05:20.387] [HTTP] Serving 'list' from job
[@00:09:13.384] [HTTP] Serving 'logs' from job`

Mounting of SD fails. LittleFS fails. And 'upload' path not found.

**Comment by GippokratOA** [comment] 2022-03-22 14:31
Despite all this, commands that send single characters still work.

**Comment by tobozo** [comment] 2022-03-22 15:02
> [00:03:06.848] LittleFS failed!

LittleFS partition wasn't created: you have to use the Arduino Sketch Data Upload utility at least once so it gets formatted.

[Arduino ESP32 filesystem uploader plugin](https://github.com/lorol/arduino-esp32fs-plugin)

> [00:03:06.464] SD Card Mount Failed

`sd_diskio.cpp` isn't patched, just overwrite it with [this version](https://github.com/espressif/arduino-esp32/blob/bb7df04446679c3c52015abaea133319e2de4178/libraries/SD/src/sd_diskio.cpp) then **remove the SD, perform a full power cycle, and reinsert the SD**.

**Comment by GippokratOA** [comment] 2022-03-22 16:01
Yep, now everything looks fine.

**Comment by GippokratOA** [comment] 2022-03-22 16:09
Ah no. When I try to run some script with 'GUI r' it just sends keystrokes 'GR' and then continues the execution.

**Comment by GippokratOA** [comment] 2022-03-22 16:27
Also when try to write 'WINDOWS' in web ui, it doesnt do anyting.

**Comment by GippokratOA** [comment] 2022-03-22 17:04
Tried on another laptop with linux. Still nothing.

**Comment by tobozo** [comment] 2022-03-23 11:26
@GippokratOA thanks for your time in testing this, the modifiers and single key behaviours are mixed up indeed, I'll look into that.

**Comment by tobozo** [comment] 2022-03-24 16:59
I've found the reason why the modifiers were being ignored: the parser was using `pressKey` instead of `pressModifier` :facepalm: 

It should be fixed now

Thanks again all for your thorough testing and your patience.

**Comment by tobozo** [comment] 2022-03-24 17:37
@Ciph3rCat @GippokratOA @j1t077 can you confirm all issues highlighted in this thread are solved so I can close it?

**Comment by GippokratOA** [comment] 2022-03-24 18:01
Yep, everything looks good. I have already rickrolled myself at least 10 times.

**Comment by GippokratOA** [comment] 2022-03-24 18:28
Ah wait..
It looks like one more problem.
It is not possible to run two scripts one for the other.
When you run the first script, it works fine but the second just repeats the first. 
For example: I have tried to run first script that changes the language of keyboard with alt + shift. It worked fine, but then I ran the second script with rickroll, it just repeated the first script: changed the language of keyboard.

**Comment by GippokratOA** [comment] 2022-03-24 18:31
Now every script repeats the change of language. But the reinsert of the stick restarts the cycle.

**Comment by GippokratOA** [comment] 2022-03-24 19:03
In logs it says that it runs only the lang change script several times.

**Comment by tobozo** [comment] 2022-03-24 20:16
last commit should hopefully fix that, also I've added a ducky example script for KDE

**Comment by GippokratOA** [comment] 2022-03-24 20:36
Yeeh thanks. Hope there are no more critical bugs.

**Comment by tobozo** [comment] 2024-03-11 12:51
closing this as solved, feel free to reopen and/or add followup

**Closed as completed by tobozo** 2024-03-11 12:51 UTC
